# swagger.yml

openapi: 3.0.0
info:
    title: "Bouffe Action REST API"
    description: "An API to handle Bouffe-Action's workflow"
    version: "1.0.0"

servers:
    - url: "/api"

components:
    schemas:
        Entity:
            type: "object"
            required:
                - eid
                - ename
                - etype
            properties:
                eid:
                    type: "string"
                ename:
                    type: "string"
                etype:
                    type: "string"
        EntityType:
            type: "string"
            enum:
                - provider
                - product

    parameters:
        eid:
            name: "eid"
            description: "Entity Code"
            in: path
            required: True
            schema:
                type: "string"
        etype:
            name: "etype"
            description: "Entity Code"
            in: path
            required: True
            schema:
                $ref: "#/components/schemas/EntityType"

paths:
    /v1/ping:
        get:
            operationId: "app.api.utility.ping"
            tags:
                - "Utility"
            summary: "Returns a ping"
            responses:
                "200":
                    description: "Successfully get a ping"

    /v1/entity:
        post:
            operationId: "app.api.entity.create_entity"
            tags:
                - "entities"
            summary: "Add new entity"
            requestBody:
                description: "Create new entity"
                required: True
                content:
                    application/json:
                        schema:
                            x-body-name: "entity"
                            $ref: "#/components/schemas/Entity"
            responses:
                "201":
                    description: "Sucessful creation"
                "406":
                    description: "Another entity with this code already exists"
    /v1/entities:
        get:
            operationId: "app.api.entity.get_entities"
            tags:
                - "entities"
            summary: "Return list of know entities"
            responses:
                "200":
                    description: "Return list of know entities"

    /v1/entities/{etype}:
        get:
            operationId: "app.api.entity.get_entities_by_type"
            tags:
                - "entities"
            parameters:
                - $ref: "#/components/parameters/etype"
            summary: "Return list of know entities"
            responses:
                "200":
                    description: "Return list of know entities"

    /v1/entity/{eid}:
        get:
            operationId: "app.api.entity.get_one_entity"
            tags:
                - "entities"
            summary: "Returns the details regarding an entity"
            parameters:
                - $ref: "#/components/parameters/eid"
            responses:
                "201":
                    description: "Returns the detailed of specified entity"
                "406":
                    description: "This entity doesnt' exists"
        delete:
            operationId: "app.api.entity.delete_one_entity"
            tags:
                - "entities"
            summary: "Delete an entity"
            parameters:
                - $ref: "#/components/parameters/eid"
            responses:
                "201":
                    description: "Entity was deleted sucessfully"
                "406":
                    description: "Entity doesn't exists"
        put:
            operationId: "app.api.entity.update_one_entity"
            tags:
                - "entities"
            summary: "Update an entity"
            requestBody:
                description: "Entity to be updated"
                required: True
                content:
                    application/json:
                        schema:
                            x-body-name: "entity"
                            $ref: "#/components/schemas/Entity"
            responses:
                "201":
                    description: "Entity updated sucessfully"
                "406":
                    description: "Entity doesn't exists"

    /v1/scale/:
        get:
            operationId: "app.api.scale.get_scale"
            tags:
                - "scale"
            summary: "Returns the current value read by scale "
            responses:
                "201":
                    description: "Current read value"
